export  const ActionTypes = {
//Common
LOADING_STARTED: 'LOADING_STARTED',
LOADING_STOPPED: 'LOADING_STOPPED',

//Survey List
SURVEYLIST_LOADED: 'SURVEYLIST_LOADED',

//Survey
SURVEY_SELECTED: 'SURVEY_SELECTED',
ADD_QUESTION: 'ADD_QUESTION',
DELETE_QUESTION: 'DELETE_QUESTION',
OPEN_QUESTION_FORM: 'OPEN_QUESTION_FORM',
CLOSE_QUESTION_FORM: 'CLOSE_QUESTION_FORM',

// Question FORM
SAVE_QUESTION: 'SAVE_QUESTION',
VALIDATE_QUESTION: 'VALIDATE_QUESTION',
};